# This file was generated by GoReleaser. DO NOT EDIT.
cask "swytch" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "bd544e45d4626587a474f78e96ae08629973fd5819745cb093350b7d09b03ad5"
      url "https://github.com/swytchdb/cache/releases/download/v#{version}/swytch_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "44f854815fb22b4e5a86283a4f09519d5e2d589ed03ddee87e6a8f5c073d9656"
      url "https://github.com/swytchdb/cache/releases/download/v#{version}/swytch_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "455c73deb475b7cb9e56139991104663ac5e282f2eb3b1e94ac407939baa44f3"
      url "https://github.com/swytchdb/cache/releases/download/v#{version}/swytch_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "91c62c1eefc28d3d77b6cff644f78cdb7a47c9c1059eb1d2862faeb7eddf42ef"
      url "https://github.com/swytchdb/cache/releases/download/v#{version}/swytch_#{version}_linux_arm64.tar.gz"
    end
  end

  name "swytch"
  desc "Distributed cache and database with Redis, Memcached, and SQL frontends"
  homepage "https://github.com/swytchdb/cache"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swytch"

  # No zap stanza required

end
