# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swytch < Formula
  desc "Distributed cache and database with Redis, Memcached, and SQL frontends"
  homepage "https://github.com/swytchdb/swytch"
  version "1.1.2"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swytchdb/swytch/releases/download/v1.1.2/swytch_1.1.2_darwin_x86_64.tar.gz"
      sha256 "2f5531a1ad3fdb60f86ea43599a9d2d16d277891767feaa6b73ce1c8ec48864e"

      define_method(:install) do
        bin.install "swytch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swytchdb/swytch/releases/download/v1.1.2/swytch_1.1.2_darwin_arm64.tar.gz"
      sha256 "c3673080ec019e2bf4379fd7afb8994ed73c966d9ca1a32b321d1cf22510a7aa"

      define_method(:install) do
        bin.install "swytch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swytchdb/swytch/releases/download/v1.1.2/swytch_1.1.2_linux_x86_64.tar.gz"
      sha256 "7bf7051c3b70248affaca288110d64d1343a955926154fe75b530dcf33375b62"
      define_method(:install) do
        bin.install "swytch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swytchdb/swytch/releases/download/v1.1.2/swytch_1.1.2_linux_arm64.tar.gz"
      sha256 "500f6d423a2294a2de9b9c211e751eda867f8f34783836bf513f1bfbab73cbca"
      define_method(:install) do
        bin.install "swytch"
      end
    end
  end

  test do
    system "#{bin}/swytch", "--version"
  end
end
