# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swytch < Formula
  desc "Distributed cache and database with Redis, Memcached, and SQL frontends"
  homepage "https://github.com/swytchdb/cache"
  version "0.1.1"
  license "AGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/swytchdb/cache/releases/download/v0.1.1/swytch_0.1.1_darwin_x86_64.tar.gz"
      sha256 "fb0cbbf4ac7e04e98cb6097241d29edfd592757363383b50119a5318786728e9"

      define_method(:install) do
        bin.install "swytch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/swytchdb/cache/releases/download/v0.1.1/swytch_0.1.1_darwin_arm64.tar.gz"
      sha256 "d06a2465b071709a0c43331c012be4df8dcab4d786777d5502951cf347142f41"

      define_method(:install) do
        bin.install "swytch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swytchdb/cache/releases/download/v0.1.1/swytch_0.1.1_linux_x86_64.tar.gz"
      sha256 "169ebb3a9bae6c0fab544cf1fb766772243dc69636459511be3f6bac8a7dc45c"
      define_method(:install) do
        bin.install "swytch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swytchdb/cache/releases/download/v0.1.1/swytch_0.1.1_linux_arm64.tar.gz"
      sha256 "30c1b537081a4fbf6c155197d96591b714054f4cb953103479e6e068fc29286d"
      define_method(:install) do
        bin.install "swytch"
      end
    end
  end

  test do
    system "#{bin}/swytch", "--version"
  end
end
